# Create the workflows directory if it doesn't exist
mkdir -p .github/workflows

# Create the pull-request.yaml file with the content matching your project
cat > .github/workflows/pull-request.yaml << 'EOF'
name: "Pull Request"
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
env:
  NODE_VERSION: 20
jobs:
  lint-test:
    name: "Lint and Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: "Setup pnpm"
        uses: "pnpm/action-setup@v2"
        with:
          version: 8

      - name: "Install Dependencies"
        run: pnpm install

      - name: "Lint"
        run: pnpm lint

      - name: "Build"
        run: pnpm build
EOF

# Add, commit, and push
git add .github/workflows/pull-request.yaml
git commit -m "Add pull request workflow for Next.js frontend"
git push origin feature/test-ci
